sample: E11S
outdir: /ix1/ylee/shared/organized_experiments/simpleleaf_runs/E11S

paths:
  conda_bin: /ix1/ylee/kor11/tools/af_tutorial/conda_env/bin
  alevin_fry_home: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/af_home

indices:
  gex: /ix1/ylee/kor11/tools/af_tutorial/E14S_simpleaf/mouse-2024-A_splici/index
  adt: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/adt_feature_index_quant/index

fastq:
  gex:
    r1: /ix1/ylee/shared/E11_12_13S/Lee, Youjin/2026/Lee-Y_03_31_2026_fastq/E11S_GEX_S1_R1_001.fastq.gz
    r2: /ix1/ylee/shared/E11_12_13S/Lee, Youjin/2026/Lee-Y_03_31_2026_fastq/E11S_GEX_S1_R2_001.fastq.gz
  adt:
    r1: /ix1/ylee/shared/E11_12_13S/Lee, Youjin/2026/Lee-Y_03_31_2026_fastq/E11S_ADT_S4_R1_001.fastq.gz
    r2: /ix1/ylee/shared/E11_12_13S/Lee, Youjin/2026/Lee-Y_03_31_2026_fastq/E11S_ADT_S4_R2_001.fastq.gz

feature_ref: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/new_feature_ref_quant.csv

chemistry:
  gex: 10xv4-3p
  adt: e14s-adt-10xv4

quant:
  threads: 64
  min_reads: 10
  resolution: cr-like
  min_gex_umi: 100

ocm:
  enabled: false
