sample: E9S
outdir: /ix1/ylee/shared/organized_experiments/simpleleaf_runs/E9S

paths:
  conda_bin: /ix1/ylee/kor11/tools/af_tutorial/conda_env/bin
  alevin_fry_home: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/af_home

indices:
  gex: /ix1/ylee/kor11/tools/af_tutorial/E14S_simpleaf/mouse-2024-A_splici/index
  adt: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/adt_feature_index_quant/index

fastq:
  gex:
    r1: /ix1/ylee/shared/E5-E10_GEX/01.RawData/E9S_GEX/E9S_GEX-SI_TT_D4_2353LWLT4_S8_L006_R1_001.fastq.gz
    r2: /ix1/ylee/shared/E5-E10_GEX/01.RawData/E9S_GEX/E9S_GEX-SI_TT_D4_2353LWLT4_S8_L006_R2_001.fastq.gz
  adt:
    r1: /ix1/ylee/shared/E5_E8_E9_E10_ADT/01.RawData/E9S_ADT/E9S_ADT_S1_L006_R1_001.fastq.gz
    r2: /ix1/ylee/shared/E5_E8_E9_E10_ADT/01.RawData/E9S_ADT/E9S_ADT_S1_L006_R2_001.fastq.gz

feature_ref: /ix1/ylee/kor11/tools/af_tutorial/E28S_simpleaf/new_feature_ref_quant.csv

chemistry:
  gex: 10xv3
  adt: e14s-adt-10xv3

quant:
  threads: 64
  min_reads: 10
  resolution: cr-like
  min_gex_umi: 100

ocm:
  enabled: false
